<a href="https://www.kaggle.com/code/nicolasfalcone/summit-2026-anemia-gustavo-e-falcone?scriptVersionId=350445349" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Summit 2026 - Anemia 
**Turma:** 6B

**Responsáveis:** Nicolas Falcone e Gustavo Palmeira de Jesus Junior

---
*Análise de Classificação utilizando Support Vector Machine (SVM)*

In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder

# Buscando caminho correto
caminho_arquivo = ""
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        if filename.endswith('.csv'):
            caminho_arquivo = os.path.join(dirname, filename)
            print(f"Arquivo encontrado e carregado: {caminho_arquivo}")
            break

df = pd.read_csv(caminho_arquivo)

Arquivo encontrado e carregado: /kaggle/input/datasets/ehababoelnaga/anemia-types-classification/diagnosed_cbc_data_v4.csv

In [2]:
print("--- Primeiras linhas do Dataset ---")
display(df.head())

print("\n--- Informações Gerais ---")
df.info()

print("\n--- Estatísticas Descritivas ---")
display(df.describe())

--- Primeiras linhas do Dataset ---

,WBC,LYMp,NEUTp,LYMn,NEUTn,RBC,HGB,HCT,MCV,MCH,MCHC,PLT,PDW,PCT,Diagnosis
0,10.0,43.2,50.1,4.3,5.0,2.77,7.3,24.2,87.7,26.3,30.1,189.0,12.5,0.17,Normocytic hypochromic anemia
1,10.0,42.4,52.3,4.2,5.3,2.84,7.3,25.0,88.2,25.7,20.2,180.0,12.5,0.16,Normocytic hypochromic anemia
2,7.2,30.7,60.7,2.2,4.4,3.97,9.0,30.5,77.0,22.6,29.5,148.0,14.3,0.14,Iron deficiency anemia
3,6.0,30.2,63.5,1.8,3.8,4.22,3.8,32.8,77.9,23.2,29.8,143.0,11.3,0.12,Iron deficiency anemia
4,4.2,39.1,53.7,1.6,2.3,3.93,0.4,316.0,80.6,23.9,29.7,236.0,12.8,0.22,Normocytic hypochromic anemia

--- Informações Gerais ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1281 entries, 0 to 1280
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   WBC        1281 non-null   float64
 1   LYMp       1281 non-null   float64
 2   NEUTp      1281 non-null   float64
 3   LYMn       1281 non-null   float64
 4   NEUTn      1281 non-null   float64
 5   RBC        1281 non-null   float64
 6   HGB        1281 non-null   float64
 7   HCT        1281 non-null   float64
 8   MCV        1281 non-null   float64
 9   MCH        1281 non-null   float64
 10  MCHC       1281 non-null   float64
 11  PLT        1281 non-null   float64
 12  PDW        1281 non-null   float64
 13  PCT        1281 non-null   float64
 14  Diagnosis  1281 non-null   object
dtypes: float64(14), object(1)
memory usage: 150.2+ KB

--- Estatísticas Descritivas ---

,WBC,LYMp,NEUTp,LYMn,NEUTn,RBC,HGB,HCT,MCV,MCH,MCHC,PLT,PDW,PCT
count,1281.000000,1281.000000,1281.000000,1281.000000,1281.000000,1281.000000,1281.000000,1281.0000,1281.000000,1281.000000,1281.000000,1281.000000,1281.000000,1281.000000
mean,7.862717,25.845000,77.511000,1.880760,5.140940,4.708267,12.184551,46.1526,85.793919,32.084840,31.739149,229.981421,14.312512,0.260280
std,3.564466,7.038728,147.746273,1.335689,2.872294,2.817200,3.812897,104.8861,27.177663,111.170756,3.300352,93.019336,3.005079,0.685351
min,0.800000,6.200000,0.700000,0.200000,0.500000,1.360000,-10.000000,2.0000,-79.300000,10.900000,11.500000,10.000000,8.400000,0.010000
25%,6.000000,25.845000,71.100000,1.880760,5.100000,4.190000,10.800000,39.2000,81.200000,25.500000,30.600000,157.000000,13.300000,0.170000
50%,7.400000,25.845000,77.511000,1.880760,5.140940,4.600000,12.300000,46.1526,86.600000,27.800000,32.000000,213.000000,14.312512,0.260280
75%,8.680000,25.845000,77.511000,1.880760,5.140940,5.100000,13.500000,46.1526,90.200000,29.600000,32.900000,293.000000,14.700000,0.260280
max,45.700000,91.400000,5317.000000,41.800000,79.000000,90.800000,87.100000,3715.0000,990.000000,3117.000000,92.800000,660.000000,97.000000,13.600000

In [3]:
print("--- Contagem de Dados Ausentes (Antes) ---")
print(df.isnull().sum())

for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

df = df.drop_duplicates()

print("\n--- Contagem de Dados Ausentes (Depois) ---")
print(df.isnull().sum())
print("--- Classes Únicas na Coluna de Diagnóstico ---")
print(df['Diagnosis'].unique())

le = LabelEncoder()
df['Diagnosis_Encoded'] = le.fit_transform(df['Diagnosis'])

mapeamento = dict(zip(le.classes_, le.transform(le.classes_)))
print("\n--- Mapeamento do Encoding ---")
for chave, valor in mapeamento.items():
    print(f"{chave}: {valor}")

df = df.drop(columns=['Diagnosis'])

print("\n--- Dataset pronto para o SVM ---")
display(df.head())

--- Contagem de Dados Ausentes (Antes) ---
WBC          0
LYMp         0
NEUTp        0
LYMn         0
NEUTn        0
RBC          0
HGB          0
HCT          0
MCV          0
MCH          0
MCHC         0
PLT          0
PDW          0
PCT          0
Diagnosis    0
dtype: int64

--- Contagem de Dados Ausentes (Depois) ---
WBC          0
LYMp         0
NEUTp        0
LYMn         0
NEUTn        0
RBC          0
HGB          0
HCT          0
MCV          0
MCH          0
MCHC         0
PLT          0
PDW          0
PCT          0
Diagnosis    0
dtype: int64
--- Classes Únicas na Coluna de Diagnóstico ---
['Normocytic hypochromic anemia' 'Iron deficiency anemia'
 'Other microcytic anemia' 'Leukemia' 'Healthy' 'Thrombocytopenia'
 'Normocytic normochromic anemia' 'Leukemia with thrombocytopenia'
 'Macrocytic anemia']

--- Mapeamento do Encoding ---
Healthy: 0
Iron deficiency anemia: 1
Leukemia: 2
Leukemia with thrombocytopenia: 3
Macrocytic anemia: 4
Normocytic hypochromic anemia: 5
Normocytic normochromic anemia: 6
Other microcytic anemia: 7
Thrombocytopenia: 8

--- Dataset pronto para o SVM ---

,WBC,LYMp,NEUTp,LYMn,NEUTn,RBC,HGB,HCT,MCV,MCH,MCHC,PLT,PDW,PCT,Diagnosis_Encoded
0,10.0,43.2,50.1,4.3,5.0,2.77,7.3,24.2,87.7,26.3,30.1,189.0,12.5,0.17,5
1,10.0,42.4,52.3,4.2,5.3,2.84,7.3,25.0,88.2,25.7,20.2,180.0,12.5,0.16,5
2,7.2,30.7,60.7,2.2,4.4,3.97,9.0,30.5,77.0,22.6,29.5,148.0,14.3,0.14,1
3,6.0,30.2,63.5,1.8,3.8,4.22,3.8,32.8,77.9,23.2,29.8,143.0,11.3,0.12,1
4,4.2,39.1,53.7,1.6,2.3,3.93,0.4,316.0,80.6,23.9,29.7,236.0,12.8,0.22,5

In [4]:
if 'Diagnosis' in df.columns:
    print("--- Classes Únicas na Coluna de Diagnóstico ---")
    print(df['Diagnosis'].unique())

    le = LabelEncoder()
    df['Diagnosis_Encoded'] = le.fit_transform(df['Diagnosis'])

    mapeamento = dict(zip(le.classes_, le.transform(le.classes_)))
    print("\n--- Mapeamento do Encoding ---")
    for chave, valor in mapeamento.items():
        print(f"{chave}: {valor}")

    df = df.drop(columns=['Diagnosis'])
    print("\n--- Dataset pronto para o SVM ---")
else:
    print("--- A coluna 'Diagnosis' já foi convertida e removida previamente. ---")

display(df.head())

--- A coluna 'Diagnosis' já foi convertida e removida previamente. ---

,WBC,LYMp,NEUTp,LYMn,NEUTn,RBC,HGB,HCT,MCV,MCH,MCHC,PLT,PDW,PCT,Diagnosis_Encoded
0,10.0,43.2,50.1,4.3,5.0,2.77,7.3,24.2,87.7,26.3,30.1,189.0,12.5,0.17,5
1,10.0,42.4,52.3,4.2,5.3,2.84,7.3,25.0,88.2,25.7,20.2,180.0,12.5,0.16,5
2,7.2,30.7,60.7,2.2,4.4,3.97,9.0,30.5,77.0,22.6,29.5,148.0,14.3,0.14,1
3,6.0,30.2,63.5,1.8,3.8,4.22,3.8,32.8,77.9,23.2,29.8,143.0,11.3,0.12,1
4,4.2,39.1,53.7,1.6,2.3,3.93,0.4,316.0,80.6,23.9,29.7,236.0,12.8,0.22,5